name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '**'
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/unit_tests
          python -m unittest test_my_utils

  run_function_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/function_tests
          ./test_print_fires.sh

  run_style_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3



#      - name: autopep8
#        uses: peter-evans/autopep8@v2
#        with:
#            args: --recursive --in-place --aggressive --aggressive .